### ISSUE TITLE
URL not accessible 

### ISSUE THREAD

**Issue by Eric-Baruch** [mehrhardt/spdhg#1]
The URL:

http://store.maths.cam.ac.uk/DAMTP/me404/data_sets/cms.mat

from which the images are downloaded (as in **example_rof.py**) is not accessible. I tried this on different computers (Windows 10) and with different web browsers.

**Comment by mehrhardt** [comment]
Thanks @Eric-Baruch for the comment. This is an issue of the contributions package of https://github.com/odlgroup/odl which is https://github.com/odlgroup/odl/tree/master/odl/contrib/datasets/images rather than this specific code. Nevertheless I contacted the Cambridge IT team to resolve this issue.
