### ISSUE TITLE
How can I solve the error:"valuererror: arange: cannot compute length. "

### ISSUE THREAD

**Issue by dylan-404** [mehrhardt/spdhg#2]
Hi, I am studying your paper these days. When ploting the iter, I get the error "valuererror: arange: cannot computer length." This happens in other examples too. So how can I correct the code ? 
The pdf file is the output of example_rof.
Looking forward to your reply! Thank you!

[example_rof_issuse.pdf](https://github.com/mehrhardt/spdhg/files/3995300/example_rof_issuse.pdf)

**Comment by mehrhardt** [comment]
Thanks for pointing out this bug which was due to an incompatibility with python >=3.6 and recent numpy. I have corrected the code, see https://github.com/mehrhardt/spdhg/commit/e786136ce550842499a6ff7cf8380a25517d0b01.

**Comment by mickilovski** [comment]
I am also getting this error 'arange: cannot compute length'. Strange thing is, there is no issue running this from my Windows environment, but when running on an EC2 instance after building a docker image, it returns this issue. I have updated to the latest libraries and modules.

**Comment by mehrhardt** [comment]
Thanks for pointing this out. Where do get the error? Are you using the latest version of the code? What version of python and numpy are you using?

**Comment by mickilovski** [comment]
Thank you for the prompt reply.

I have a Docker image created with a miniconda environment using Numpy 1.25.0 and Python 3.10.11. My workflow runs using some Numpy arrays to generate some raster images for some GIS work.

Note, this works when in certain situations in certain different scenarios, however it does not work for a specific scenario. I do however think it may be memory related, because initially it did not work for any scenario. But when I increased the RAM to my AWS E1C2 instance, certain scenarios are now running. So I will try increase again to see if I have any luck. Will get back to you and let you know.

**Comment by mickilovski** [comment]
> Thanks for pointing this out. Where do get the error? Are you using the latest version of the code? What version of python and numpy are you using?

Thank you for the prompt reply.

I have a Docker image created with a miniconda environment using Numpy 1.25.0 and Python 3.10.11. My workflow runs using some Numpy arrays to generate some raster images for some GIS work.

Note, this works when in certain situations in certain different scenarios, however it does not work for a specific scenario. I do however think it may be memory related, because initially it did not work for any scenario. But when I increased the RAM to my AWS EC2 instance, certain scenarios are now running. So I will try increase again to see if I have any luck. Will get back to you and let you know.
